ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.hophey.MonitoringKt.configureMonitoring
      - com.hophey.SerializationKt.configureSerialization
      - com.hophey.plugins.SecurityKt.configureSecurity
